name: pontos
description: "Um aplicativo para gerenciar pontos de umbanda "
publish_to: 'none'
version: 1.0.19

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  supabase_flutter: ^2.8.2
  sqflite: ^2.4.1
  path: ^1.9.0
  provider: ^6.1.2
  connectivity_plus: ^6.1.0
  uuid: ^4.5.1
  google_fonts: ^6.2.1
  audioplayers: ^6.0.0
  file_picker: ^8.1.4
  mime: ^1.0.6
  permission_handler: ^11.3.0
  path_provider: ^2.1.2
  http: ^1.2.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  logger: ^2.6.2
  audio_service: ^0.18.18
  google_sign_in: 6.2.1
  shared_preferences: ^2.5.4
  youtube_player_flutter: ^9.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/splash.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/






