name: pontos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.8.2
  sqflite: ^2.4.1
  path: ^1.9.0
  provider: ^6.1.2
  connectivity_plus: ^6.1.0
  uuid: ^4.5.1
  google_fonts: ^6.2.1
  audioplayers: ^6.0.0
  file_picker: ^8.1.4
  mime: ^1.0.6
  permission_handler: ^11.3.0
  path_provider: ^2.1.2
  http: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/splash.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
